//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Web.Resources.Areas.LibraryBlog.Models.WorkSchedules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkSchedulesFormModelResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkSchedulesFormModelResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Web.Resources.Areas.LibraryBlog.Models.WorkSchedules.WorkSchedulesFormMod" +
                            "elResx", typeof(WorkSchedulesFormModelResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name in bulgarian.
        /// </summary>
        public static string DepartmentNameBg {
            get {
                return ResourceManager.GetString("DepartmentNameBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name in english.
        /// </summary>
        public static string DepartmentNameEn {
            get {
                return ResourceManager.GetString("DepartmentNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field can&apos;t be longer than {1} symbols..
        /// </summary>
        public static string MaxLengthErrorMsg {
            get {
                return ResourceManager.GetString("MaxLengthErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field can&apos;t be shorter than {1} symbols..
        /// </summary>
        public static string MinLengthErrorMsg {
            get {
                return ResourceManager.GetString("MinLengthErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        public static string RequiredErrorMsg {
            get {
                return ResourceManager.GetString("RequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday work time in bulgarian.
        /// </summary>
        public static string SaturdayBg {
            get {
                return ResourceManager.GetString("SaturdayBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday work time in english.
        /// </summary>
        public static string SaturdayEn {
            get {
                return ResourceManager.GetString("SaturdayEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday work time in bulgarian.
        /// </summary>
        public static string SundayBg {
            get {
                return ResourceManager.GetString("SundayBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday work time in english.
        /// </summary>
        public static string SundayEn {
            get {
                return ResourceManager.GetString("SundayEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work days schedule in bulgarian.
        /// </summary>
        public static string WorkdaysBg {
            get {
                return ResourceManager.GetString("WorkdaysBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work days schedule in english.
        /// </summary>
        public static string WorkdaysEn {
            get {
                return ResourceManager.GetString("WorkdaysEn", resourceCulture);
            }
        }
    }
}
