//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Web.Resources.Areas.LibraryBlog.Models.Employees {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeFormModelResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeFormModelResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Web.Resources.Areas.LibraryBlog.Models.Employees.EmployeeFormModelResx", typeof(EmployeeFormModelResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentStructures {
            get {
                return ResourceManager.GetString("DepartmentStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string EmployeeDepartmentStructureId {
            get {
                return ResourceManager.GetString("EmployeeDepartmentStructureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee name in bulgarian.
        /// </summary>
        public static string EmployeeNameBg {
            get {
                return ResourceManager.GetString("EmployeeNameBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee name in english.
        /// </summary>
        public static string EmployeeNameEn {
            get {
                return ResourceManager.GetString("EmployeeNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number in department.
        /// </summary>
        public static string EmployeeOrder {
            get {
                return ResourceManager.GetString("EmployeeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone numbers.
        /// </summary>
        public static string EmployeePhoneNumbers {
            get {
                return ResourceManager.GetString("EmployeePhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field can&apos;t be longer than {1} symbols..
        /// </summary>
        public static string MaxLengthErrorMsg {
            get {
                return ResourceManager.GetString("MaxLengthErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field can&apos;t be shorter than {1} symbols..
        /// </summary>
        public static string MinLengthErrorMsg {
            get {
                return ResourceManager.GetString("MinLengthErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        public static string RequiredErrorMsg {
            get {
                return ResourceManager.GetString("RequiredErrorMsg", resourceCulture);
            }
        }
    }
}
