//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Web.Resources.Areas.LibraryBlog.Models.LibServiceDescriptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibServiceDescriptionFormModelResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibServiceDescriptionFormModelResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Web.Resources.Areas.LibraryBlog.Models.LibServiceDescriptions.LibServiceD" +
                            "escriptionFormModelResx", typeof(LibServiceDescriptionFormModelResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in bulgarian.
        /// </summary>
        public static string DescriptionBg {
            get {
                return ResourceManager.GetString("DescriptionBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in english.
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the service type.
        /// </summary>
        public static string LibServiceTypeId {
            get {
                return ResourceManager.GetString("LibServiceTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type.
        /// </summary>
        public static string LibServiceTypes {
            get {
                return ResourceManager.GetString("LibServiceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field can&apos;t be longer than {1} symbols..
        /// </summary>
        public static string MaxLengthErrorMsg {
            get {
                return ResourceManager.GetString("MaxLengthErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field can&apos;t be shorter than {1} symbols..
        /// </summary>
        public static string MinLengthErrorMsg {
            get {
                return ResourceManager.GetString("MinLengthErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Info in bulgarian.
        /// </summary>
        public static string PriceInfoBg {
            get {
                return ResourceManager.GetString("PriceInfoBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price info in english.
        /// </summary>
        public static string PriceInfoEn {
            get {
                return ResourceManager.GetString("PriceInfoEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        public static string RequiredErrorMsg {
            get {
                return ResourceManager.GetString("RequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order type in bulgarian.
        /// </summary>
        public static string ServiceTypeBg {
            get {
                return ResourceManager.GetString("ServiceTypeBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order type in english.
        /// </summary>
        public static string ServiceTypeEn {
            get {
                return ResourceManager.GetString("ServiceTypeEn", resourceCulture);
            }
        }
    }
}
